// Google Apps Script - Email Subscription Scanner v2
// Updated: Include invoices/receipts + better logging
// Deploy: https://script.google.com/home
// Run on EACH Gmail account you want to scan

// 🎯 Keywords to FIND subscriptions (EXPANDED)
const KEYWORDS = [
  'subscription', 'recurring', 'monthly charge', 'billing',
  'renewing', 'auto-renew', 'you are being charged',
  'your subscription', 'cancel anytime', 'payment received',
  'receipt', 'invoice', 'order confirmation', 'charged',
  'payment', 'paid', 'transaction', 'debit'
];

// 🚫 Keywords to EXCLUDE (Newsletters, marketing)
const EXCLUDE_KEYWORDS = [
  'unsubscribe', 'newsletter', 'marketing', 'promotions',
  'offer', 'deal', 'discount', 'special'
];

function findSubscriptions() {
  const startTime = new Date();
  let allSubscriptions = [];
  const seen = new Set();
  let scannedCount = 0;
  let errorLog = [];
  
  Logger.log('🚀 Starting subscription scan...');
  Logger.log('📧 Account: ' + Session.getActiveUser().getEmail());
  
  try {
    // Search all emails (last 2 years) - more results
    Logger.log('🔍 Searching emails...');
    const threads = GmailApp.search('after:2023/01/01', 0, 500);
    scannedCount = threads.length;
    Logger.log(`📬 Found ${scannedCount} threads to scan`);
    
    let matchCount = 0;
    
    threads.forEach((thread, index) => {
      if (index % 100 === 0) {
        Logger.log(`📊 Progress: ${index}/${scannedCount}`);
      }
      
      try {
        const messages = thread.getMessages();
        const latest = messages[messages.length - 1];
        const subject = latest.getSubject().toLowerCase();
        const from = latest.getFrom().toLowerCase();
        const date = latest.getDate();
        const body = latest.getPlainBody().toLowerCase();
        
        // Check if it matches subscription keywords
        const hasKeyword = KEYWORDS.some(k => 
          subject.includes(k) || body.includes(k) || from.includes(k)
        );
        const hasExclude = EXCLUDE_KEYWORDS.some(k => subject.includes(k));
        
        if (hasKeyword && !hasExclude) {
          matchCount++;
          
          // Extract sender email
          const emailMatch = from.match(/([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)/);
          const email = emailMatch ? emailMatch[1].toLowerCase() : from;
          
          // Skip Gmail/Google emails
          if (email.includes('gmail.com') || email.includes('google.com')) {
            return;
          }
          
          // Extract service name
          const domain = email.split('@')[1] || '';
          const serviceName = domain.split('.')[0].toUpperCase();
          
          if (!seen.has(email)) {
            seen.add(email);
            allSubscriptions.push({
              service: serviceName || subject.slice(0, 40),
              email: email,
              date: date,
              subject: latest.getSubject(),
              snippet: latest.getPlainBody().slice(0, 300)
            });
          }
        }
      } catch (e) {
        errorLog.push('Thread error: ' + e.message);
      }
    });
    
    Logger.log(`🎯 Matched ${matchCount} emails`);
    
    // Sort by date (newest first)
    allSubscriptions.sort((a, b) => b.date - a.date);
    
    // Remove duplicates by email
    allSubscriptions = allSubscriptions.filter((item, index, self) =>
      index === self.findIndex((t) => t.email === item.email)
    );
    
    // Generate report
    const report = allSubscriptions.map((s, i) => 
      `${i + 1}. 📦 ${s.service}\n   📧 ${s.email}\n   📅 ${s.date.toLocaleDateString()}\n   📝 ${s.subject}`
    ).join('\n\n');
    
    const summary = `
╔══════════════════════════════════════════════╗
║     📋 SUBSCRIPTION SCAN REPORT v2           ║
╚══════════════════════════════════════════════╝

👤 Account: ${Session.getActiveUser().getEmail()}
📊 Emails Scanned: ${scannedCount}
🎯 Potential Subscriptions Found: ${allSubscriptions.length}
⏱️ Scan Time: ${((new Date() - startTime) / 1000).toFixed(1)}s

${report ? '━━━━━━━━━━━━━━━━━━━━━━━━\n\n' + report : '❌ No subscriptions found'}

═══════════════════════════════════════════════
Generated by Orland • ${new Date().toLocaleString()}
    `;
    
    Logger.log(`📧 Sending email report...`);
    MailApp.sendEmail({
      to: Session.getActiveUser().getEmail(),
      subject: `📋 Subscription Scan v2: ${allSubscriptions.length} found`,
      body: summary
    });
    Logger.log('✅ Email sent!');
    
    // Also log to Google Sheets if available
    try {
      const sheet = SpreadsheetApp.openById('YOUR_SPREADSHEET_ID').getSheetByName('Subscriptions');
      if (sheet) {
        allSubscriptions.forEach(s => {
          sheet.appendRow([s.service, s.email, s.date, s.subject]);
        });
      }
    } catch (e) {
      Logger.log('⚠️ Could not write to spreadsheet');
    }
    
    return {
      success: true,
      scanned: scannedCount,
      found: allSubscriptions.length,
      subscriptions: allSubscriptions
    };
    
  } catch (error) {
    Logger.log('❌ Error: ' + error.message);
    MailApp.sendEmail({
      to: Session.getActiveUser().getEmail(),
      subject: '❌ Subscription Scanner Error',
      body: `Error: ${error.message}\n\nStack: ${error.stack}`
    });
    return { success: false, error: error.message };
  }
}

// To run: Select function → ▶️ Run
// To see logs: View → Logs